const nodes = [
  {
    id: 'root-learning',
    rootId: 'root-learning',
    parentId: null,
    parentMessageId: null,
    title: 'LLM 학습 전략',
    description: 'LLM으로 어려운 개념을 학습하는 중심 대화이다.',
    sessionId: 'session-root-learning',
    createdAt: '09:00',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'learning-context',
    rootId: 'root-learning',
    parentId: 'root-learning',
    parentMessageId: 'root-learning-message-2',
    title: '컨텍스트 관리',
    description: '긴 대화에서 본래 질문을 유지하는 방법을 다룬다.',
    sessionId: 'session-learning-context',
    createdAt: '09:12',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'learning-example',
    rootId: 'root-learning',
    parentId: 'learning-context',
    parentMessageId: 'learning-context-message-2',
    title: '예시 비교',
    description: '같은 질문을 단일 흐름과 분기 흐름으로 비교한다.',
    sessionId: 'session-learning-example',
    createdAt: '09:25',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'learning-side-question',
    rootId: 'root-learning',
    parentId: 'root-learning',
    parentMessageId: 'root-learning-message-1',
    title: '용어 질문',
    description: '학습 중 나온 낯선 용어를 별도로 정리한다.',
    sessionId: 'session-learning-side-question',
    createdAt: '09:31',
    isActive: false,
    isHidden: false,
  },
  {
    id: 'root-project',
    rootId: 'root-project',
    parentId: null,
    parentMessageId: null,
    title: '프로젝트 기획',
    description: '학회 프로젝트의 서비스 요구사항을 정리하는 시작점이다.',
    sessionId: 'session-root-project',
    createdAt: '10:00',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-user-flow',
    rootId: 'root-project',
    parentId: 'root-project',
    parentMessageId: 'root-project-message-2',
    title: '사용자 흐름',
    description: '시작 노드, 세션 진입, 미니 그래프 이동을 정리한다.',
    sessionId: 'session-project-user-flow',
    createdAt: '10:08',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-graph-policy',
    rootId: 'root-project',
    parentId: 'project-user-flow',
    parentMessageId: 'project-user-flow-message-2',
    title: '그래프 정책',
    description: 'main 경로 계산과 전체화면 전환 기준을 다룬다.',
    sessionId: 'session-project-graph-policy',
    createdAt: '10:16',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-api',
    rootId: 'root-project',
    parentId: 'project-user-flow',
    parentMessageId: 'project-user-flow-message-1',
    title: 'API 연동',
    description: '실제 LLM API로 교체 가능한 호출 계층을 검토한다.',
    sessionId: 'session-project-api',
    createdAt: '10:20',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-test',
    rootId: 'root-project',
    parentId: 'project-graph-policy',
    parentMessageId: 'project-graph-policy-message-2',
    title: '검증 계획',
    description: '사용자 테스트와 빌드 검증 기준을 정리한다.',
    sessionId: 'session-project-test',
    createdAt: '10:28',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-metrics',
    rootId: 'root-project',
    parentId: 'project-test',
    parentMessageId: 'project-test-message-2',
    title: '지표 설계',
    description: '사용자가 중심 흐름을 잃지 않는지 측정하는 지표이다.',
    sessionId: 'session-project-metrics',
    createdAt: '10:34',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-ui',
    rootId: 'root-project',
    parentId: 'project-graph-policy',
    parentMessageId: 'project-graph-policy-message-1',
    title: 'UI 분업',
    description: '컴포넌트 단위 분업을 위한 경계와 책임을 정리한다.',
    sessionId: 'session-project-ui',
    createdAt: '10:40',
    isActive: true,
    isHidden: false,
  },
  {
    id: 'project-rollout',
    rootId: 'root-project',
    parentId: 'project-api',
    parentMessageId: 'project-api-message-2',
    title: '적용 순서',
    description: '문서화, UI 기틀, 검증, 후속 API 연동 순서를 정리한다.',
    sessionId: 'session-project-rollout',
    createdAt: '10:46',
    isActive: true,
    isHidden: false,
  },
]

const sessions = nodes.map((node) => ({
  id: node.sessionId,
  nodeId: node.id,
  messages: [
    {
      id: `${node.id}-message-1`,
      role: 'user',
      content: `${node.title}에 대해 정리해줘.`,
      createdAt: node.createdAt,
    },
    {
      id: `${node.id}-message-2`,
      role: 'assistant',
      content: `${node.description} 현재 노드는 독립 세션이며 그래프에서 1:1로 연결된다.`,
      createdAt: node.createdAt,
    },
  ],
}))

export function createInitialGraphState() {
  return {
    nodes,
    sessions,
    activeNodeId: 'root-project',
    selectedRootNodeId: 'root-project',
    mainTargetNodeIdByRoot: {
      'root-learning': 'learning-example',
      'root-project': 'project-metrics',
    },
    events: [],
  }
}
